--
-- File generated with SQLiteStudio v3.2.1 on qua fev 20 13:18:29 2019
--
-- Text encoding used: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: TB_DIVIDAS
DROP TABLE IF EXISTS TB_DIVIDAS;

CREATE TABLE TB_DIVIDAS (
    ID         INTEGER         PRIMARY KEY AUTOINCREMENT,
    DATAINICIO VARCHAR (10)    NOT NULL,
    QTDPARCELA INTEGER (10)    NOT NULL,
    VALORTOTAL DECIMAL (50, 2) NOT NULL,
    DESCRICAO  VARCHAR (250)   NOT NULL,
    ID_LOGIN   INTEGER (10)    REFERENCES TB_LOGIN (ID) ON DELETE CASCADE
                               NOT NULL
);

INSERT INTO TB_DIVIDAS (ID, DATAINICIO, QTDPARCELA, VALORTOTAL, DESCRICAO, ID_LOGIN) VALUES (41, '20/02/2019', 5, 19, 'teste Drop Table', 4);

-- Table: TB_ENTRADA_VALORES
DROP TABLE IF EXISTS TB_ENTRADA_VALORES;

CREATE TABLE TB_ENTRADA_VALORES (
    ID                INTEGER         NOT NULL
                                      PRIMARY KEY AUTOINCREMENT,
    VALOR_ENTRADA     DECIMAL (50, 2) NOT NULL,
    DESCRICAO_ENTRADA VARCHAR (150)   NOT NULL,
    DATA_ENTRADA      VARCHAR (10)    NOT NULL,
    ID_LOGIN          INTEGER         REFERENCES TB_LOGIN (ID),
    STATUS_ENTRADA    BOOLEAN
);


-- Table: TB_LOGIN
DROP TABLE IF EXISTS TB_LOGIN;

CREATE TABLE TB_LOGIN (
    ID      INTEGER       PRIMARY KEY AUTOINCREMENT
                          NOT NULL,
    USUARIO VARCHAR (100) NOT NULL,
    SENHA   VARCHAR (20)  NOT NULL
);

INSERT INTO TB_LOGIN (ID, USUARIO, SENHA) VALUES (4, 'ELIAS', 'RUxJQVMxMjM=');
INSERT INTO TB_LOGIN (ID, USUARIO, SENHA) VALUES (5, 'DIEGO', 'RElFR08xMjM=');

-- Table: TB_PARCELAS
DROP TABLE IF EXISTS TB_PARCELAS;

CREATE TABLE TB_PARCELAS (
    ID           INTEGER         PRIMARY KEY AUTOINCREMENT
                                 NOT NULL,
    NRPARCELA    INTEGER         NOT NULL,
    VALORPARCELA DECIMAL (50, 2) NOT NULL,
    DATAVENC     STRING          NOT NULL,
    STATUS_PAGO  BOOLEAN         NOT NULL
                                 DEFAULT (0),
    ID_DIVIDA    INTEGER         REFERENCES TB_DIVIDAS (ID) ON DELETE CASCADE
                                                            ON UPDATE CASCADE
                                 NOT NULL
);

INSERT INTO TB_PARCELAS (ID, NRPARCELA, VALORPARCELA, DATAVENC, STATUS_PAGO, ID_DIVIDA) VALUES (1, 1, 3.8, '20/02/2019', 0, 41);
INSERT INTO TB_PARCELAS (ID, NRPARCELA, VALORPARCELA, DATAVENC, STATUS_PAGO, ID_DIVIDA) VALUES (2, 2, 3.8, '20/03/2019', 0, 41);
INSERT INTO TB_PARCELAS (ID, NRPARCELA, VALORPARCELA, DATAVENC, STATUS_PAGO, ID_DIVIDA) VALUES (3, 3, 3.8, '20/04/2019', 0, 41);
INSERT INTO TB_PARCELAS (ID, NRPARCELA, VALORPARCELA, DATAVENC, STATUS_PAGO, ID_DIVIDA) VALUES (4, 4, 3.8, '20/05/2019', 0, 41);
INSERT INTO TB_PARCELAS (ID, NRPARCELA, VALORPARCELA, DATAVENC, STATUS_PAGO, ID_DIVIDA) VALUES (5, 5, 3.8, '20/06/2019', 0, 41);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
